# Generated by Django 5.1.4 on 2024-12-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_downvote_user_alter_upvote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
