# Generated by Django 5.1.4 on 2025-07-15 13:13

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250715_1834'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove the old CharField fields
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user',
        ),
    ]
