# Generated by Django 5.1.4 on 2025-07-15 13:13

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20250715_1843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 2: Rename ForeignKey fields and add constraints/indexes
        migrations.RenameField(
            model_name='blogpost',
            old_name='author_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_fk',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='user_fk',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='downvote',
            old_name='user_fk',
            new_name='user',
        ),
        # Add unique constraints for votes
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together={('post', 'user')},
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author'], name='blog_blogpost_author_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='blog_comment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['user'], name='blog_upvote_user_idx'),
        ),
        migrations.AddIndex(
            model_name='downvote',
            index=models.Index(fields=['user'], name='blog_downvote_user_idx'),
        ),
    ]
